spring:
  application:
    name: rbac

  datasource:
    url: jdbc:mysql://localhost:3306/rbac
    username: <your_mysql_username>
    password: <your_mysql_password>

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: debug